version: "3"

services:
  ckan-dev:
    container_name: ckan-dev
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./ckanext:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
    environment:
      - VIRTUAL_HOST=ckan.localhost

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"

  redis:
    container_name: redis
    image: redis:alpine

  nginx-proxy:
    build: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      # - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  ckan_storage:
  pg_data:
